'use client'
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { nutritionApi } from '@/lib/api'
const GROUPS=[{id:'protein',label:'Proteins',emoji:'🥩',accent:'#d85a30',accentBg:'#faece7',accentText:'#993c1d',desc:'High-protein foods for muscle building, recovery, and satiety.',foods:['Chicken Breast','Salmon','Eggs','Greek Yogurt','Turkey Breast','Shrimp','Cottage Cheese','Tempeh','Canned Tuna','Lentils','Edamame','Sardines','Whey Protein','Peanut Butter','Tofu','Black Beans','Egg Whites','Ground Beef','Lamb Chop','Parmesan Cheese']},{id:'carbs',label:'Carbs & Grains',emoji:'🌾',accent:'#ba7517',accentBg:'#faeeda',accentText:'#633806',desc:'Complex carbohydrates for sustained energy, fiber, and workout fuel.',foods:['Brown Rice','Rolled Oats','Sweet Potato','Whole Wheat Pasta','Quinoa','Banana','Chickpeas','Corn','Barley','White Rice','Buckwheat','Whole Grain Bread','Granola','Green Peas','Popcorn','Millet','Plantain','Cassava','Cream of Wheat','Whole Wheat Tortilla']},{id:'produce',label:'Produce',emoji:'🥦',accent:'#3b6d11',accentBg:'#eaf3de',accentText:'#27500a',desc:'Fruits and vegetables packed with vitamins, minerals, and antioxidants.',foods:['Broccoli','Strawberries','Red Bell Pepper','Kale','Avocado','Tomato','Carrot','Spinach','Blueberries','Garlic','Eggplant','Cucumber','Lemon Juice','Kiwi','Onion','Romaine Lettuce','Zucchini','Orange','Beets','Brussels Sprouts']},{id:'dairy',label:'Dairy & Fats',emoji:'🥛',accent:'#185fa5',accentBg:'#e6f1fb',accentText:'#0c447c',desc:'Calcium-rich dairy and healthy fats for hormones, brain, and joint health.',foods:['Whole Milk','Cheddar Cheese','Kefir','Olive Oil','Almonds','Walnuts','Sunflower Seeds','Pumpkin Seeds','Cashews','Flaxseeds','Feta Cheese','Skim Milk','Butter','Coconut Oil','Ricotta Cheese','Ghee','Fish Oil','Low-Fat Yogurt','Cream Cheese','Sour Cream']},{id:'supplements',label:'Supplements',emoji:'💊',accent:'#534ab7',accentBg:'#eeedfe',accentText:'#3c3489',desc:'Common supplements for athletic performance, recovery, and micronutrient gaps.',foods:['Whey Protein Isolate','Creatine Monohydrate','Caffeine','Beta-Alanine','Vitamin D','Magnesium','Collagen Peptides','Ashwagandha','Electrolytes','Plant Protein','MCT Oil','Vitamin C','Vitamin B12','Rhodiola Rosea','Green Tea Extract','Fish Oil Capsule','ZMA','Glutamine','HMB','Probiotics']}]
const EMOJIS:Record<string,string>={'Chicken Breast':'🍗','Salmon':'🐟','Eggs':'🥚','Greek Yogurt':'🫙','Turkey Breast':'🦃','Shrimp':'🐚','Cottage Cheese':'🐄','Tempeh':'🌱','Canned Tuna':'🟫','Lentils':'🫘','Edamame':'🫛','Sardines':'🦑','Whey Protein':'💊','Peanut Butter':'🥜','Tofu':'🥣','Black Beans':'🫐','Egg Whites':'🐔','Ground Beef':'🥩','Lamb Chop':'🐑','Parmesan Cheese':'🧀','Brown Rice':'🍚','Rolled Oats':'🌾','Sweet Potato':'🍠','Whole Wheat Pasta':'🍝','Quinoa':'🟡','Banana':'🍌','Chickpeas':'🫘','Corn':'🌽','Barley':'🟤','White Rice':'🍚','Buckwheat':'🌰','Whole Grain Bread':'🫓','Granola':'🥣','Green Peas':'🫛','Popcorn':'🌽','Millet':'🌾','Plantain':'🍠','Cassava':'🍠','Cream of Wheat':'🫙','Whole Wheat Tortilla':'🟫','Broccoli':'🥦','Strawberries':'🍓','Red Bell Pepper':'🫑','Kale':'🥬','Avocado':'🥑','Tomato':'🍅','Carrot':'🥕','Spinach':'🫙','Blueberries':'🫐','Garlic':'🧅','Eggplant':'🍆','Cucumber':'🥒','Lemon Juice':'🍋','Kiwi':'🥝','Onion':'🧄','Romaine Lettuce':'🥗','Zucchini':'🫑','Orange':'🍊','Beets':'🥜','Brussels Sprouts':'🥬','Whole Milk':'🥛','Cheddar Cheese':'🧀','Kefir':'🫙','Olive Oil':'🫒','Almonds':'🥜','Walnuts':'🌰','Sunflower Seeds':'🌻','Pumpkin Seeds':'🌻','Cashews':'🥜','Flaxseeds':'🫘','Feta Cheese':'🧀','Skim Milk':'🥛','Butter':'🧈','Coconut Oil':'🥥','Ricotta Cheese':'🧈','Ghee':'🧈','Fish Oil':'🐟','Low-Fat Yogurt':'🥣','Cream Cheese':'🫙','Sour Cream':'🥚','Whey Protein Isolate':'💊','Creatine Monohydrate':'🌿','Caffeine':'☕','Beta-Alanine':'🧬','Vitamin D':'☀️','Magnesium':'🧲','Collagen Peptides':'🫐','Ashwagandha':'🌿','Electrolytes':'🧊','Plant Protein':'🌱','MCT Oil':'🫚','Vitamin C':'🍋','Vitamin B12':'💙','Rhodiola Rosea':'🌿','Green Tea Extract':'🍃','Fish Oil Capsule':'🧡','ZMA':'💊','Glutamine':'🌾','HMB':'🍖','Probiotics':'🧫'}
const BENEFITS:Record<string,{pos:string[],neg:string[]}>={'Chicken Breast':{pos:['Complete protein with all 9 essential amino acids for muscle synthesis','Low in saturated fat supporting heart health'],neg:['May contain antibiotic residues if conventionally raised — choose organic']},'Salmon':{pos:['Omega-3 fatty acids reduce inflammation and muscle soreness','Vitamin D supports bone density and immune function'],neg:['Higher mercury than smaller fish — limit to 2-3 servings per week']},'Eggs':{pos:['Choline is critical for brain function and liver health','Leucine-rich — ideal post-workout muscle repair'],neg:['High dietary cholesterol — consult doctor if cardiovascular risk present']},'Broccoli':{pos:['Sulforaphane activates the most powerful antioxidant pathway in the body','Vitamin C exceeds oranges by weight — critical for collagen synthesis'],neg:['Can cause bloating when suddenly increased — introduce gradually']},'Avocado':{pos:['Monounsaturated oleic acid is the most heart-healthy fat available','Highest potassium food available — prevents muscle cramps'],neg:['Calorie-dense — track portions carefully during fat loss phases']},'Blueberries':{pos:['Anthocyanins improve blood flow to the brain and boost memory','May reduce post-exercise muscle damage and speed recovery'],neg:['High natural sugar — limit to 1 cup; choose frozen for better value']},'Almonds':{pos:['Highest vitamin E content of any tree nut','Magnesium at 19% daily value supports muscle function and sleep'],neg:['Calorie-dense — measure by weight; 1 oz is only about 23 almonds']},'Olive Oil':{pos:['Oleocanthal has anti-inflammatory effects comparable to ibuprofen','Oleic acid is the Mediterranean diet cornerstone for heart health'],neg:['Low smoke point for EVOO — use for finishing or low-heat cooking only']},'Whey Protein Isolate':{pos:['Fastest absorbed protein — peak amino acids in blood within 60 minutes','Highest leucine density maximizes muscle protein synthesis'],neg:['Dairy-derived — not suitable for vegans or the lactose-intolerant']},'Creatine Monohydrate':{pos:['Most researched supplement — improves high-intensity performance by 10-15%','Faster ATP regeneration enables more reps and heavier sets'],neg:['Causes intracellular water retention — weight gain is normal and beneficial']}}
const DEFAULT_BENEFIT={pos:['Rich in essential nutrients supporting your fitness goals','Contains key vitamins and minerals for optimal performance'],neg:['Always check ingredients for personal allergens and dietary restrictions']}
export function NutritionTab(){
  const[group,setGroup]=useState(GROUPS[0])
  const[food,setFood]=useState<string|null>(null)
  const[search,setSearch]=useState('')
  const[flash,setFlash]=useState(false)
  const[fdcId,setFdcId]=useState<string|null>(null)
  const[autoSet,setAutoSet]=useState(false)
  const{data:searchData,isFetching:searching}=useQuery({queryKey:['usda-search',food],queryFn:()=>nutritionApi.search(food!),enabled:!!food,staleTime:86400000})
  const{data:factsData,isFetching:loadingFacts}=useQuery({queryKey:['usda-facts',fdcId],queryFn:()=>nutritionApi.getFacts(fdcId!),enabled:!!fdcId,staleTime:86400000})
  const firstResult=searchData?.results?.[0]
  if(firstResult&&!autoSet&&food){setFdcId(String(firstResult.fdcId));setAutoSet(true)}
  const selectFood=(name:string)=>{setFlash(true);setFdcId(null);setAutoSet(false);setTimeout(()=>{setFood(name);setFlash(false)},220)}
  const filtered=group.foods.filter(f=>f.toLowerCase().includes(search.toLowerCase()))
  const nl=factsData?.nutritionLabel
  const isLoading=searching||loadingFacts
  const nfRows=nl?[{b:true,label:`Total Fat ${nl.totalFat?.value??0}g`,pct:`${nl.totalFat?.dv??0}%`},{b:false,i:true,label:`Saturated Fat ${nl.saturatedFat?.value??0}g`,pct:`${nl.saturatedFat?.dv??0}%`},{b:false,i:true,label:`Trans Fat 0g`,pct:''},{b:true,label:`Cholesterol ${nl.cholesterol?.value??0}mg`,pct:`${nl.cholesterol?.dv??0}%`},{b:true,label:`Sodium ${nl.sodium?.value??0}mg`,pct:`${nl.sodium?.dv??0}%`},{b:true,label:`Total Carbohydrate ${nl.totalCarbs?.value??0}g`,pct:`${nl.totalCarbs?.dv??0}%`},{b:false,i:true,label:`Dietary Fiber ${nl.dietaryFiber?.value??0}g`,pct:`${nl.dietaryFiber?.dv??0}%`},{b:false,i:true,label:`Total Sugars ${nl.totalSugars?.value??0}g`,pct:''},{b:true,label:`Protein ${nl.protein?.value??0}g`,pct:''}]:[]
  const prot=nl?.protein?.value??0,carb=nl?.totalCarbs?.value??0,fat=nl?.totalFat?.value??0,fiber=nl?.dietaryFiber?.value??0,cals=nl?.calories??0
  const total=fat*9+carb*4+prot*4||1
  const macros=nl?[{label:'Protein',val:`${prot}g`,pct:Math.round((prot*4/total)*100),color:'#185fa5'},{label:'Carbs',val:`${carb}g`,pct:Math.round((carb*4/total)*100),color:'#ba7517'},{label:'Fat',val:`${fat}g`,pct:Math.round((fat*9/total)*100),color:'#d85a30'},{label:'Fiber',val:`${fiber}g`,pct:Math.min(100,Math.round((fiber/28)*100)),color:'#3b6d11'}]:[]
  const benefits=food?(BENEFITS[food]||DEFAULT_BENEFIT):null
  const emoji=food?(EMOJIS[food]||'🥗'):group.emoji
  const g=group as any
  return(<div style={{display:'flex',flexDirection:'column',gap:16}}>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{GROUPS.map(gr=>(<button key={gr.id} onClick={()=>{setGroup(gr);setFood(null);setFdcId(null);setAutoSet(false);setSearch('')}} style={{padding:'8px 18px',borderRadius:20,fontSize:13,fontWeight:800,border:`2px solid ${gr.id===group.id?gr.accent:'var(--border)'}`,background:gr.id===group.id?gr.accentBg:'var(--bg)',color:gr.id===group.id?gr.accentText:'var(--muted)',cursor:'pointer',fontFamily:'Nunito,sans-serif',display:'flex',alignItems:'center',gap:7,transition:'all 0.15s'}}><span style={{fontSize:18}}>{gr.emoji}</span>{gr.label}</button>))}</div>
    <div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{fontSize:12,fontWeight:700,color:'var(--muted)'}}>{g.desc}</div><div style={{fontSize:11,fontWeight:700,color:'var(--s-dark)',background:'var(--s-light)',padding:'3px 10px',borderRadius:20}}>📡 Live USDA data</div></div>
    <div style={{display:'grid',gridTemplateColumns:'260px 1fr',gap:18,alignItems:'start'}}>
      <div style={{background:'var(--card)',border:'2px solid var(--border)',borderRadius:16,overflow:'hidden'}}>
        <input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${g.label.toLowerCase()}...`} style={{width:'100%',padding:'10px 13px',border:'none',borderBottom:'2px solid var(--border)',fontSize:13,fontWeight:700,background:'var(--bg)',color:'var(--text)',outline:'none',fontFamily:'Nunito,sans-serif'}}/>
        <div style={{maxHeight:460,overflowY:'auto'}}>{filtered.map((f:string)=>(<div key={f} onClick={()=>selectFood(f)} style={{display:'flex',alignItems:'center',gap:10,padding:'10px 13px',cursor:'pointer',borderBottom:'1.5px solid var(--border)',background:food===f?g.accentBg:'transparent',transition:'background 0.1s'}}><span style={{fontSize:22,width:28,textAlign:'center',flexShrink:0}}>{EMOJIS[f]||'🥗'}</span><div style={{flex:1}}><div style={{fontSize:13,fontWeight:800,color:food===f?g.accentText:'var(--text)'}}>{f}</div><div style={{fontSize:10,color:'var(--muted)',fontWeight:700}}>{food===f&&isLoading?'⏳ Loading live data...':'Click for live USDA nutrition facts'}</div></div>{food===f&&isLoading&&<div style={{width:8,height:8,borderRadius:'50%',background:g.accent}}/>}</div>))}</div>
      </div>
      <div style={{display:'flex',flexDirection:'column',gap:14}}>
        <div style={{height:160,borderRadius:18,overflow:'hidden',position:'relative',background:`linear-gradient(135deg,${g.accentBg},var(--bg))`,border:'2px solid var(--border)',display:'flex',alignItems:'center',justifyContent:'center'}}>
          <span style={{fontSize:90,transition:'opacity 0.22s',opacity:flash?0:1}}>{emoji}</span>
          <div style={{position:'absolute',bottom:0,left:0,right:0,padding:'8px 16px',background:'rgba(0,0,0,0.4)',display:'flex',justifyContent:'space-between',alignItems:'center'}}>
            <span style={{fontSize:14,fontWeight:800,color:'#fff'}}>{food||'Select a food'}</span>
            <div style={{display:'flex',gap:6}}>{food&&<span style={{fontSize:11,fontWeight:800,padding:'2px 10px',borderRadius:20,background:g.accent,color:'#fff'}}>{g.label}</span>}{food&&factsData&&<span style={{fontSize:10,fontWeight:800,padding:'2px 8px',borderRadius:20,background:'rgba(255,255,255,0.2)',color:'#fff'}}>📡 USDA Live</span>}</div>
          </div>
        </div>
        {food&&isLoading?(<div style={{background:'var(--card)',border:'2px solid var(--border)',borderRadius:18,padding:40,textAlign:'center'}}><div style={{fontSize:40,marginBottom:12}}>⏳</div><div style={{fontSize:15,fontWeight:900,color:'var(--text)',marginBottom:6}}>Fetching live USDA data...</div><div style={{fontSize:12,color:'var(--muted)',fontWeight:700}}>Pulling real nutritional info for {food} from USDA FoodData Central</div></div>
        ):food&&nl?(<>
          <div style={{background:'var(--card)',border:'2px solid var(--border)',borderRadius:18,padding:16}}>
            <div style={{display:'flex',alignItems:'center',gap:8,marginBottom:10,padding:'6px 10px',background:'var(--s-light)',borderRadius:10}}><span style={{fontSize:14}}>📡</span><span style={{fontSize:11,fontWeight:700,color:'var(--s-dark)'}}>Live data from USDA FoodData Central · {factsData?.description}</span></div>
            <div style={{fontFamily:'Arial,sans-serif',border:'1.5px solid var(--text)',borderRadius:3,padding:'10px 14px',color:'var(--text)',maxWidth:320}}>
              <div style={{fontSize:22,fontWeight:900,borderBottom:'7px solid var(--text)',paddingBottom:2,marginBottom:2}}>Nutrition Facts</div>
              <div style={{fontSize:11,marginBottom:1}}>{nl.servingDesc||'Per serving'}</div>
              <div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',borderBottom:'3px solid var(--text)',paddingBottom:2,marginBottom:3}}><div><div style={{fontSize:12,fontWeight:900}}>Amount per serving</div><div style={{fontSize:13,fontWeight:900}}>Calories</div></div><div style={{fontSize:38,fontWeight:900,lineHeight:1}}>{Math.round(cals)}</div></div>
              <div style={{textAlign:'right',fontSize:10,fontWeight:900,borderBottom:'2px solid var(--text)',paddingBottom:1,marginBottom:2}}>% Daily Value*</div>
              {nfRows.map((r:any,i:number)=>(<div key={i} style={{display:'flex',justifyContent:'space-between',fontSize:11,borderBottom:'0.5px solid #ccc',padding:`1.5px 0 1.5px ${r.i?14:0}px`,fontWeight:r.b?900:400}}><span>{r.label}</span><span>{r.pct}</span></div>))}
              <div style={{fontSize:9,color:'var(--muted)',textAlign:'center',borderTop:'1px solid var(--text)',marginTop:4,paddingTop:3}}>*% Daily Value based on a 2,000 calorie diet.</div>
            </div>
          </div>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{macros.map((m:any)=>(<div key={m.label} style={{background:'var(--bg)',border:'2px solid var(--border)',borderRadius:12,padding:'11px 13px'}}><div style={{fontSize:11,color:'var(--muted)',fontWeight:700,marginBottom:4}}>{m.label}</div><div style={{fontSize:17,fontWeight:900,color:'var(--text)',marginBottom:6}}>{m.val}</div><div style={{height:6,background:'var(--border)',borderRadius:20,overflow:'hidden'}}><div style={{height:'100%',width:`${m.pct}%`,background:m.color,borderRadius:20,transition:'width 0.5s ease'}}/></div></div>))}</div>
          {benefits&&(<div style={{background:'var(--card)',border:'2px solid var(--border)',borderRadius:18,padding:16}}><div style={{fontSize:14,fontWeight:900,color:'var(--text)',marginBottom:8}}>🌿 Health & fitness benefits</div>{benefits.pos.map((t:string,i:number)=>(<div key={i} style={{display:'flex',gap:8,marginTop:8,alignItems:'flex-start'}}><span style={{fontSize:10,fontWeight:800,padding:'2px 8px',borderRadius:20,background:'var(--p-light)',color:'var(--p-dark)',whiteSpace:'nowrap',flexShrink:0}}>✓ Benefit</span><span style={{fontSize:12,color:'var(--muted)',lineHeight:1.55,fontWeight:700}}>{t}</span></div>))}{benefits.neg.map((t:string,i:number)=>(<div key={i} style={{display:'flex',gap:8,marginTop:8,alignItems:'flex-start'}}><span style={{fontSize:10,fontWeight:800,padding:'2px 8px',borderRadius:20,background:'#FFE8E8',color:'#C62A2A',whiteSpace:'nowrap',flexShrink:0}}>⚠ Caution</span><span style={{fontSize:12,color:'var(--muted)',lineHeight:1.55,fontWeight:700}}>{t}</span></div>))}</div>)}
        </>):(<div style={{background:'var(--card)',border:'2px solid var(--border)',borderRadius:18,padding:40,textAlign:'center'}}><div style={{fontSize:52,marginBottom:12}}>{g.emoji}</div><div style={{fontSize:16,fontWeight:900,color:'var(--text)',marginBottom:6}}>{g.foods.length} {g.label}</div><div style={{fontSize:13,color:'var(--muted)',fontWeight:700,marginBottom:12}}>Click any food to get live nutrition data from the USDA FoodData Central database.</div><div style={{display:'inline-flex',alignItems:'center',gap:6,padding:'6px 14px',background:'var(--s-light)',borderRadius:20,fontSize:12,fontWeight:700,color:'var(--s-dark)'}}>📡 400,000+ real foods · Updated live</div></div>)}
      </div>
    </div>
  </div>)
}
